### ISSUE TITLE
Does not allow content to be submitted when used in a form

### ISSUE THREAD

**Issue by braunsonm** [onepill/django-simplemde#13]
I have a simple form like so:

```python
from simplemde.widgets import SimpleMDEEditor
# from simplemde.fields import SimpleMDEEditor # Both have the same issue

class GenericForm(forms.Form):
    subject = forms.CharField(min_length=3, max_length=80, label='How can we help?',
                              help_text='Please describe what you need in brief (one sentence).')
    details = forms.CharField(widget=SimpleMDEEditor, label='Please add any details that might help us help you.')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(GenericForm, self).__init__(*args, **kwargs)
```

This form works fine if I change the widget to forms.Textarea, but it does not work with the MDEEditor widget. The submit button of the form simply does nothing.

If anyone is able to point me in the right direction it would be appreciated!

**Comment by onepill** [comment]
Hi @ChaosCA ,

I have tried with Django 2.0.1(python 3.6.4) with your form code snippet, it works find on my side, both rendering and submitting, could you paste your code in views.py and your template? and the version of django.

**Comment by braunsonm** [comment]
Thank you so much for the response @onepill 

Interestingly it works fine like I said if I simply change the widget to the forms.widgets.Textarea which makes me believe it’s something on the plugin side of things.

Not sure if this helps but clicking the submit button causes console to output `Response Recieved` in firefox from content.js

The Django version is 2.0. The rendering works fine for me IF I specifically add the CSS and JS to the template. It doesn’t do it automatically like I expected. 

View is such:
```python
def new_ticket(request, type):
    user = request.user

    _, title, form_class, type_id, _ = next((f for f in ticket_forms if f[0] == type), (None, None, None, None, None))
    if not form_class:
        raise Http404()

    if request.method == 'POST':
        form = form_class(user, request.POST)
        if form.is_valid():
            # check for rate limit here instead of the method, since we need the form to be valid to actually
            # create a ticket
            request.limited = getattr(request, 'limited', False)
            if is_ratelimited(request, key='ip', method='POST', rate='5/d', fn=new_ticket, increment=True) or \
                    is_ratelimited(request, key='user', method='POST', rate='5/d', fn=new_ticket, increment=True):
                raise Ratelimited()

            # Snipped some useless database stuff with Ticket()

            ticket.save()


            return redirect('ticket_details', ticket_id=ticket.id)
    else:
        form = form_class(user)

    return render(request, form_class.view(), {'form': form, 'title': title})
```


Template using jinja 2 and the django-bootstrap4 plugin(although it does not touch your plugin)
```
                <form  method="post">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                    <h3 class="h2 g-font-weight-300 g-mb-20">Submit a new Ticket</h3>
                    <h2>{{ title }}</h2>
                    <hr/>

                        {{ bootstrap_form(form) }}

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary rounded-0 pull-right"
                                data-disable-with="{{ data_disable_with('Creating Ticket') }}">
                            Create Ticket
                        </button>
                        <div style="clear: both"></div>
                    </div>
                </form>

<!— Snipped the <script> tags and CSS —>
```

I do not believe the view is at fault, the browser does not reload. I believe it has to do entirely with the client side of things. Perhaps Django’s form field validation now allowing the form to submit.

**Comment by onepill** [comment]
Hi 
Looks like you didn't add  {{ formset.media }} to your template file? that's how django imports required js/css files of widgets. you could see the example here: https://github.com/onepill/django-simplemde/blob/master/testproject/markdown/templates/markdown/index.html

**Comment by braunsonm** [comment]
@onepill Thanks for the response again,

That did not resolve the issue, the rending of the box is fine. But it never gets past Djangos client side form validation it seems. None of your examples seem to be using it the same way I am. I am not using it as a form generated from a model. It is using a form.py that I pasted above.

**Comment by onepill** [comment]
Hi @ChaosCA 
It's the same, the I have tried with your forms.py with the example, it works well. you could try that too. And I did added "novalidation" tag to the form. hope this could solve the issue.

**Comment by braunsonm** [comment]
Adding no validation isn't a good solution as the rest of the form would be invalid..
It's too bad we can't get this to work at all...

@onepill 😞

**Comment by braunsonm** [comment]
Any ideas?

**Comment by braunsonm** [comment]
I might have found the issue @onepill 

https://github.com/praekelt/django-recaptcha/blob/develop/captcha/fields.py#L16

Here is an example that properly supports form fields. I believe it is due to the fact that you do not have a clean method that it can validate against. And you also extend the TextField class that is NOT from forms. So it doesn't seem to work at all in forms.

**Comment by onepill** [comment]
Hi @ChaosCA sorry for the late reply. I'm now busy on company's projects which had a really tight schedule. So I don't have time to look into this issue now. So if you have a solution, please fork this repo and create a pull request with the fix. I could upload it to pypi. Thanks

**Comment by roopeshm12345** [comment]
simplemde = new SimpleMDE({forceSync: true})

**Comment by braunsonm** [comment]
Hey @roopeshm12345 was that on the widget? The field?

**Comment by roopeshm12345** [comment]
Make changes in you template. basically it will finds the first textarea inside form tag and transoform into markdown editor.

**Comment by ChaosCA** [comment]
That's not really helpful @roopeshm12345 what if you have multiple MDE fields? Also doing that in the template isn't the best since I would want my form elements to be rendered dynamically by django.

**Comment by braunsonm** [comment]
Roopeshm is right. Set the SIMPLEMDE_OPTION `forceSync` to True and it'll solve your problems.
