### ISSUE TITLE
Not showing editor in forms.

### ISSUE THREAD

**Issue by Eraldo** [onepill/django-simplemde#3]
By default the field works nicely in the admin.
In a form it shows as a plain Textfield.

The browser console reports:
`simplemde.init.js:1 Uncaught ReferenceError: django is not defined`

Any ideas?

**Comment by onepill** [comment]
Hi @Eraldo Sorry, the description was not clear enough, this project is only working with django admin right now, however your suggestion is good, will make it work from normal form as well.

Thanks

**Comment by onepill** [comment]
@Eraldo have fixed this issue, and pushed, please update to version 0.0.5, and make sure you have jQuery imported in the page.

**Comment by Eraldo** [comment]
@onepill thanks that sounds great.. I'll check it out in a minute.
I tried to do it myself for a couple of hours..
I ended up making it work in the admin and break in my CBGVs or.. making it work there and break the admin. _sigh_
So thank's a lot.

**Comment by Eraldo** [comment]
You did not push to pypi yet, did you?
Update: You did. :D
(was still my cache)

**Comment by Eraldo** [comment]
✓ Works great!
