### ISSUE TITLE
dynamic changes to the editor

### ISSUE THREAD

**Issue by Eraldo** [onepill/django-simplemde#5]
How to I get hold of the editor instance?

My javascript skills are lacking here. :|
If I change the init script to:
`var editor = new SimpleMDE(options);`
Then I can access things like `editor.codemirror`.

How do I get hold of the editor without changing the init script?
Is it somehow bound to the `.simplemde-box`?

For example: I can get to the options via `$('.simplemde-box').data().simplemdeOptions.autosave`
How can I get to the codemirror instance? Any ideas?

**Comment by onepill** [comment]
Hi @Eraldo i found this which could get CodeMirror from DOM: http://stackoverflow.com/questions/11581516/get-codemirror-instance

**Comment by onepill** [comment]
@Eraldo and I have pushed version 0.0.7 out, which you could get SimpleMDE instance like this:

``` javascript
$('.simplemde-box')[0].SimpleMDE
```
