### ISSUE TITLE
Preview looks ugly in django admin

### ISSUE THREAD

**Issue by mhozza** [onepill/django-simplemde#8]
Django admin CSS styles are mixed with the SimpleMDE CSS and the preview looks ugly in django admin.
Especially lists doesn't have any bullets, and have large left margin.

**Comment by onepill** [comment]
Hi @mhozza 
I have realized that before, but the only options i could think up were:
1. change django admin css
2. change simplemde css file
Both are not very good options, so i chose to leave it...

Thanks
